# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "screeninator"
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Druse"]
  s.date = "2013-03-15"
  s.description = "Create and manage complex screen sessions easily."
  s.email = "jon@jondruse.com"
  s.executables = ["screeninator"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/screeninator",
    "lib/screeninator.rb",
    "lib/screeninator/assets/sample.yml",
    "lib/screeninator/assets/screen_config.screen",
    "lib/screeninator/cli.rb",
    "lib/screeninator/config_writer.rb",
    "lib/screeninator/helper.rb",
    "screeninator.gemspec",
    "test/helper.rb",
    "test/test_screeninator.rb"
  ]
  s.homepage = "http://github.com/jondruse/screeninator"
  s.post_install_message = "\nThanks for installing Screeninator!\n\nUPGRADE WARNING - If you have a custom default config, move it to ~/.screeninator/defaults/\n\nRemember to add the following line to your .bashrc file\n\n[[ -s \"$HOME/.screeninator/scripts/screeninator\" ]] && source \"$HOME/.screeninator/scripts/screeninator\"\n\n"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Create and manage complex screen sessions easily."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

