# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{screeninator}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Druse"]
  s.date = %q{2010-09-22}
  s.default_executable = %q{screeninator}
  s.description = %q{Create and manage complex screen sessions easily.}
  s.email = %q{jon@jondruse.com}
  s.executables = ["screeninator"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/screeninator",
     "lib/screeninator.rb",
     "lib/screeninator/assets/sample.yml",
     "lib/screeninator/assets/screen_config.screen",
     "lib/screeninator/cli.rb",
     "lib/screeninator/config_writer.rb",
     "test/helper.rb",
     "test/test_screeninator.rb"
  ]
  s.homepage = %q{http://github.com/jondruse/screeninator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Create and manage complex screen sessions easily.}
  s.test_files = [
    "test/helper.rb",
     "test/test_screeninator.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

